# -*- coding: utf-8 -*-
"""app(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvIjbq3AKz3_v33AyG5BCPsrUUw5kfo6
"""

# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXLf6KzPizcsduMloKoIfk5kNxTsFiTh
"""

import streamlit as st
import pickle
import os
import numpy as np

# ============================================================
# KONFIGURASI HALAMAN
# ============================================================
st.set_page_config(
    page_title="Face PCA Studio",
    page_icon="🧑‍🤝‍🧑",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# LOAD MODEL (untuk statistik di Home)
# ============================================================
MODEL_PATH = "model/model.pkl"  # sesuaikan dengan lokasi model kamu

@st.cache_resource
def load_model():
    if os.path.exists(MODEL_PATH):
        with open(MODEL_PATH, "rb") as f:
            data = pickle.load(f)
        return data
    return None

model_data = load_model()

# Ambil statistik dari model, fallback ke 0 kalau model belum ada
if model_data is not None:
    n_components = model_data["pca"].n_components_
    n_identitas = len(np.unique(model_data["labels"]))
    n_total_foto = len(model_data["labels"])
else:
    n_components, n_identitas, n_total_foto = 0, 0, 0

# ============================================================
# SESSION STATE UNTUK NAVIGASI
# ============================================================
if "page" not in st.session_state:
    st.session_state.page = "Home"

def go_to(page_name):
    st.session_state.page = page_name

# ============================================================
# CSS CUSTOM — REPLIKASI DESAIN DARK BLUE
# ============================================================
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap');

    html, body, [class*="css"] {
        font-family: 'Poppins', sans-serif;
    }

    /* Background gradient utama */
    .stApp {
        background: linear-gradient(135deg, #1a1f4d 0%, #2d3480 50%, #4147a3 100%);
    }

    /* Sembunyikan header & footer default streamlit */
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}

    /* Sidebar styling */
    section[data-testid="stSidebar"] {
        background: #131635;
        border-right: 1px solid rgba(255,255,255,0.08);
    }
    section[data-testid="stSidebar"] > div {
        padding-top: 1.5rem;
    }

    /* Sidebar nav buttons */
    .nav-btn-container .stButton button {
        background: transparent;
        border: none;
        color: rgba(255,255,255,0.55);
        font-size: 1.4rem;
        width: 100%;
        padding: 0.65rem 0;
        border-radius: 10px;
        transition: all 0.2s ease;
    }
    .nav-btn-container .stButton button:hover {
        background: rgba(255,255,255,0.08);
        color: #ffffff;
    }

    /* Card umum */
    .card {
        background: rgba(20, 24, 61, 0.55);
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 18px;
        padding: 1.5rem 1.8rem;
    }

    .card-dark {
        background: rgba(10, 13, 40, 0.65);
        border-radius: 18px;
        padding: 1.5rem 1.8rem;
        border: 1px solid rgba(255,255,255,0.06);
    }

    /* About badge */
    .about-badge {
        background: #2dd4bf;
        color: #0a0d28;
        font-weight: 700;
        font-size: 0.7rem;
        padding: 0.25rem 0.7rem;
        border-radius: 6px;
        display: inline-flex;
        align-items: center;
        gap: 6px;
        letter-spacing: 0.05em;
    }

    .title-pill {
        background: rgba(20, 24, 61, 0.7);
        border-radius: 20px;
        padding: 1rem 2rem;
        text-align: center;
        border: 1px solid rgba(255,255,255,0.08);
    }

    .title-pill h1 {
        color: white;
        font-size: 2.1rem;
        font-weight: 800;
        margin: 0;
        letter-spacing: 0.02em;
    }

    /* Stat number cards */
    .stat-box {
        background: rgba(10, 13, 40, 0.6);
        border-radius: 14px;
        padding: 1rem 1.2rem;
        text-align: center;
        border: 1px solid rgba(255,255,255,0.06);
    }
    .stat-label {
        color: rgba(255,255,255,0.65);
        font-size: 0.78rem;
        font-weight: 500;
        margin-bottom: 0.3rem;
    }
    .stat-value {
        color: white;
        font-size: 2.3rem;
        font-weight: 700;
        line-height: 1;
    }

    /* Feature card kiri bawah (clickable) */
    .feature-card {
        background: rgba(10, 13, 40, 0.6);
        border-radius: 16px;
        padding: 1.1rem 1.3rem;
        border: 1px solid rgba(255,255,255,0.07);
        margin-bottom: 0.9rem;
        transition: all 0.2s ease;
        cursor: pointer;
    }
    .feature-card:hover {
        background: rgba(45, 212, 191, 0.12);
        border-color: rgba(45, 212, 191, 0.4);
    }
    .feature-title {
        color: white;
        font-size: 1.05rem;
        font-weight: 600;
        margin-bottom: 0.2rem;
    }
    .feature-desc {
        color: rgba(255,255,255,0.6);
        font-size: 0.82rem;
        line-height: 1.4;
    }

    .section-heading {
        color: white;
        font-size: 1.3rem;
        font-weight: 700;
        margin-bottom: 0.6rem;
    }
    .section-text {
        color: rgba(255,255,255,0.75);
        font-size: 0.95rem;
        line-height: 1.7;
    }

    /* Feature card button override (full width, transparent) */
    div[data-testid="stVerticalBlockBorderWrapper"] .stButton button {
        width: 100%;
        background: transparent;
        border: none;
        color: white;
        text-align: left;
        padding: 0;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================
# SIDEBAR — ICON NAVIGASI
# ============================================================
with st.sidebar:
    st.markdown("<div style='text-align:center; margin-bottom: 1.5rem;'>"
                "<span style='font-size:1.6rem;'>🫂</span></div>", unsafe_allow_html=True)

    st.markdown('<div class="nav-btn-container">', unsafe_allow_html=True)

    if st.button("🏠", key="nav_home", help="Home", use_container_width=True):
        go_to("Home")
    if st.button("📊", key="nav_eda", help="EDA & Visualisasi", use_container_width=True):
        go_to("EDA")
    if st.button("🔍", key="nav_compare", help="Bandingkan Dua Wajah", use_container_width=True):
        go_to("Compare")
    if st.button("🗜️", key="nav_compress", help="Kompresi Gambar", use_container_width=True):
        go_to("Compress")

    st.markdown('</div>', unsafe_allow_html=True)

    st.markdown("<div style='position:fixed; bottom:1.5rem; text-align:center; width:13rem;'>"
                "<span style='font-size:1.4rem;'>🌙</span></div>", unsafe_allow_html=True)

# ============================================================
# HALAMAN: HOME
# ============================================================
def show_home():
    # Baris atas: ABOUT card + Title + Illustration
    col_about, col_illust = st.columns([2.1, 1])

    with col_about:
        st.markdown(f"""
        <div class="card" style="height: 100%;">
            <span class="about-badge">ABOUT ⓘ</span>
            <h2 style="color:white; font-weight:700; margin-top:1rem;">Face PCA Studio</h2>
            <p class="section-text">
                Eksplorasi wajah manusia lewat Principal Component Analysis (PCA) dan
                Singular Value Decomposition (SVD) — dari eigenfaces sampai kompresi gambar,
                semuanya interaktif!
            </p>
        </div>
        """, unsafe_allow_html=True)

    with col_illust:
        st.markdown("""
        <div class="card" style="height: 100%; display:flex; align-items:center; justify-content:center;">
            <span style="font-size: 5rem;">🧑‍🤝‍🧑</span>
        </div>
        """, unsafe_allow_html=True)

    # Title pill di tengah (mengikuti desain, judul besar di atas)
    st.markdown("""
    <div class="title-pill" style="margin: 1.2rem 0;">
        <h1>FACE PCA STUDIO</h1>
    </div>
    """, unsafe_allow_html=True)

    st.write("")

    # Baris bawah: kiri (3 feature cards) | kanan (tools + stats + cara kerja)
    col_left, col_right = st.columns([1, 1.6])

    with col_left:
        # Feature card 1: EDA
        with st.container(border=True):
            c1, c2 = st.columns([0.6, 4])
            with c1:
                st.markdown("<span style='font-size:1.8rem;'>📊</span>", unsafe_allow_html=True)
            with c2:
                st.markdown("""
                <div class="feature-title">EDA & Visualisasi</div>
                <div class="feature-desc">Lihat distribusi data, mean face, eigenfaces,
                dan seberapa banyak variance yang ditangkap oleh PCA.</div>
                """, unsafe_allow_html=True)
            if st.button("Buka →", key="btn_eda", use_container_width=True):
                go_to("EDA")
                st.rerun()

        # Feature card 2: Bandingkan
        with st.container(border=True):
            c1, c2 = st.columns([0.6, 4])
            with c1:
                st.markdown("<span style='font-size:1.8rem;'>🔍</span>", unsafe_allow_html=True)
            with c2:
                st.markdown("""
                <div class="feature-title">Bandingkan 2 Wajah</div>
                <div class="feature-desc">Upload dua foto dan cek apakah itu orang
                yang sama lewat cosine similarity di ruang PCA.</div>
                """, unsafe_allow_html=True)
            if st.button("Buka →", key="btn_compare", use_container_width=True):
                go_to("Compare")
                st.rerun()

        # Feature card 3: Kompresi
        with st.container(border=True):
            c1, c2 = st.columns([0.6, 4])
            with c1:
                st.markdown("<span style='font-size:1.8rem;'>🗜️</span>", unsafe_allow_html=True)
            with c2:
                st.markdown("""
                <div class="feature-title">Kompresi Gambar</div>
                <div class="feature-desc">Upload gambar apa saja dan lihat bagaimana
                SVD bisa mengompresnya dengan berbagai tingkat kualitas.</div>
                """, unsafe_allow_html=True)
            if st.button("Buka →", key="btn_compress", use_container_width=True):
                go_to("Compress")
                st.rerun()

    with col_right:
        # Tools icon + 3 stat boxes
        st.markdown('<div class="card-dark">', unsafe_allow_html=True)
        r1c1, r1c2, r1c3, r1c4 = st.columns([1.1, 1, 1, 1])
        with r1c1:
            st.markdown("<div style='text-align:center; padding-top:1rem;'>"
                        "<span style='font-size:3rem;'>🛠️</span></div>", unsafe_allow_html=True)
        with r1c2:
            st.markdown(f"""
            <div class="stat-box">
                <div class="stat-label">Komponen PCA</div>
                <div class="stat-value">{n_components}</div>
            </div>
            """, unsafe_allow_html=True)
        with r1c3:
            st.markdown(f"""
            <div class="stat-box">
                <div class="stat-label">Jumlah Identitas</div>
                <div class="stat-value">{n_identitas}</div>
            </div>
            """, unsafe_allow_html=True)
        with r1c4:
            st.markdown(f"""
            <div class="stat-box">
                <div class="stat-label">Total Foto Training</div>
                <div class="stat-value">{n_total_foto}</div>
            </div>
            """, unsafe_allow_html=True)

        st.write("")

        st.markdown("""
        <div class="section-heading">Cara Kerja Singkat</div>
        <div class="section-text">
            Setiap foto wajah diubah jadi grayscale, disamakan pencahayaannya, diubah
            ukurannya jadi 100×100 piksel, lalu diproyeksikan ke ruang PCA hasil training.
            Kemiripan dua wajah diukur lewat cosine similarity antar vektor PCA-nya —
            semakin mendekati 1, semakin mirip kedua wajah tersebut.
        </div>
        """, unsafe_allow_html=True)

        st.markdown('</div>', unsafe_allow_html=True)

    if model_data is None:
        st.warning("⚠️ Model belum ditemukan di `model/model.pkl`. Statistik di atas masih menunjukkan 0. "
                   "Upload model hasil training dari Colab ke folder `model/` di repo Streamlit kamu.")

# ============================================================
# HALAMAN LAIN (placeholder — akan diisi selanjutnya)
# ============================================================
def show_eda():
    st.title("📊 EDA & Visualisasi")
    st.info("Halaman ini akan diisi selanjutnya.")

def show_compare():
    st.title("🔍 Bandingkan Dua Wajah")
    st.info("Halaman ini akan diisi selanjutnya.")

def show_compress():
    st.title("🗜️ Kompresi Gambar (SVD)")
    st.info("Halaman ini akan diisi selanjutnya.")

# ============================================================
# ROUTER
# ============================================================
if st.session_state.page == "Home":
    show_home()
elif st.session_state.page == "EDA":
    show_eda()
elif st.session_state.page == "Compare":
    show_compare()
elif st.session_state.page == "Compress":
    show_compress()
