# -*- coding: utf-8 -*-
"""app(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvIjbq3AKz3_v33AyG5BCPsrUUw5kfo6
"""

# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXLf6KzPizcsduMloKoIfk5kNxTsFiTh
"""

import os
import io

import streamlit as st
import numpy as np
import pandas as pd
import pickle
import cv2
from PIL import Image
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity

# =========================================================
# PAGE CONFIG
# =========================================================
st.set_page_config(
    page_title="Face PCA Studio",
    page_icon="🪞",
    layout="wide",
    initial_sidebar_state="expanded",
)

# =========================================================
# CUSTOM CSS — colorful, lively theme
# =========================================================
def inject_css():
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap');

        html, body, [class*="css"] {
            font-family: 'Poppins', sans-serif;
        }

        .stApp {
            background: linear-gradient(135deg, #f5f7ff 0%, #eef2ff 45%, #fdf2ff 100%);
        }

        section[data-testid="stSidebar"] {
            background: linear-gradient(180deg, #4338ca 0%, #7c3aed 55%, #db2777 100%);
        }
        section[data-testid="stSidebar"] * {
            color: #ffffff !important;
        }
        section[data-testid="stSidebar"] label {
            background: rgba(255,255,255,0.08);
            border-radius: 12px;
            padding: 10px 14px;
            margin-bottom: 6px;
            border: 1px solid rgba(255,255,255,0.15);
            transition: all 0.2s ease;
        }
        section[data-testid="stSidebar"] label:hover {
            background: rgba(255,255,255,0.22);
            transform: translateX(4px);
        }
        section[data-testid="stSidebar"] hr {
            border-color: rgba(255,255,255,0.25);
        }

        .hero {
            padding: 2.1rem 2rem;
            border-radius: 22px;
            background: linear-gradient(120deg, #6366f1, #a855f7, #ec4899);
            color: white;
            margin-bottom: 1.6rem;
            box-shadow: 0 10px 30px rgba(99,102,241,0.25);
        }
        .hero h1 { margin: 0; font-weight: 800; font-size: 2.0rem; }
        .hero p { margin-top: 0.5rem; font-size: 1.02rem; opacity: 0.95; }

        .badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 999px;
            font-size: 0.78rem;
            font-weight: 600;
            margin-bottom: 0.6rem;
        }
        .badge-purple { background: #ede9fe; color: #6d28d9; }
        .badge-pink   { background: #fce7f3; color: #be185d; }
        .badge-blue   { background: #dbeafe; color: #1d4ed8; }
        .badge-green  { background: #dcfce7; color: #15803d; }

        div[data-testid="stMetric"] {
            background: white;
            border-radius: 14px;
            padding: 0.8rem 1rem;
            box-shadow: 0 4px 14px rgba(0,0,0,0.06);
        }

        .stButton > button {
            border-radius: 12px;
            font-weight: 600;
            background: linear-gradient(120deg, #6366f1, #ec4899);
            color: white;
            border: none;
            padding: 0.6rem 1.4rem;
            transition: all 0.2s ease;
        }
        .stButton > button:hover {
            transform: scale(1.03);
            box-shadow: 0 8px 18px rgba(99,102,241,0.35);
        }

        div[data-testid="stFileUploader"] {
            background: white;
            border-radius: 14px;
            padding: 0.6rem;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


inject_css()

# =========================================================
# LOAD MODEL
# =========================================================
MODEL_CANDIDATES = [
    "model/model_with_me.pkl",
    "model_with_me.pkl",
]


@st.cache_resource
def load_model():
    for path in MODEL_CANDIDATES:
        if os.path.exists(path):
            with open(path, "rb") as f:
                return pickle.load(f)
    return None


model = load_model()

if model is None:
    st.error(
        "⚠️ File `model_with_me.pkl` tidak ditemukan. Pastikan file berada di "
        "root project atau di folder `model/`."
    )
    st.stop()

pca = model.get("pca")
X_train_pca = model.get("X_train_pca")
y_train = model.get("y_train")
X_test_pca = model.get("X_test_pca")
y_test = model.get("y_test")
labels_all = model.get("labels")


# =========================================================
# HELPERS
# =========================================================
def preprocess(img_bytes):
    img = Image.open(io.BytesIO(img_bytes)).convert("L")
    img_arr = np.array(img)
    img_eq = cv2.equalizeHist(img_arr)
    img_blur = cv2.GaussianBlur(img_eq, (3, 3), 0)
    img_resized = cv2.resize(img_blur, (100, 100))
    return img_resized.flatten() / 255.0


def svd_compress_gray(img_arr, k):
    U, S, Vt = np.linalg.svd(img_arr, full_matrices=False)
    k = min(k, len(S))
    reconstructed = (U[:, :k] * S[:k]) @ Vt[:k, :]
    reconstructed = np.clip(reconstructed, 0, 255).astype(np.uint8)
    return reconstructed, S


def svd_compress_color(img_arr, k):
    channels = []
    s_values = None
    for c in range(3):
        ch = img_arr[:, :, c].astype(float)
        U, S, Vt = np.linalg.svd(ch, full_matrices=False)
        k_ = min(k, len(S))
        rec = (U[:, :k_] * S[:k_]) @ Vt[:k_, :]
        channels.append(np.clip(rec, 0, 255))
        if s_values is None:
            s_values = S
    reconstructed = np.stack(channels, axis=2).astype(np.uint8)
    return reconstructed, s_values


# =========================================================
# SIDEBAR NAVIGATION
# =========================================================
with st.sidebar:
    st.markdown("## 🪞 Face PCA Studio")
    st.caption("Eksplorasi wajah dengan PCA & SVD")
    st.markdown("---")
    page = st.radio(
        "Navigasi",
        [
            "🏠 Home",
            "📊 EDA & Visualisasi",
            "🔍 Bandingkan Dua Wajah",
            "🗜️ Kompresi Gambar (SVD)",
        ],
        label_visibility="collapsed",
    )
    st.markdown("---")
    st.caption("Dibuat dengan Streamlit + scikit-learn")


# =========================================================
# PAGE: HOME
# =========================================================
def render_home():
    st.markdown(
        """
        <div class="hero">
            <h1>🪞 Face PCA Studio</h1>
            <p>Eksplorasi wajah manusia lewat Principal Component Analysis (PCA) dan
            Singular Value Decomposition (SVD) — dari eigenfaces sampai kompresi gambar,
            semuanya interaktif!</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    c1, c2, c3 = st.columns(3)
    n_components = pca.n_components_ if pca is not None else "-"
    n_identities = len(np.unique(y_train)) if y_train is not None else "-"
    n_photos = len(y_train) if y_train is not None else "-"
    with c1:
        st.metric("🧩 Komponen PCA", n_components)
    with c2:
        st.metric("🧑‍🤝‍🧑 Jumlah Identitas", n_identities)
    with c3:
        st.metric("🖼️ Total Foto Training", n_photos)

    st.markdown("### Jelajahi Fitur")
    f1, f2, f3 = st.columns(3)
    features = [
        (f1, "📊", "EDA & Visualisasi", "badge-blue",
         "Lihat distribusi data, mean face, eigenfaces, dan seberapa banyak "
         "variance yang ditangkap oleh PCA."),
        (f2, "🔍", "Bandingkan Dua Wajah", "badge-purple",
         "Upload dua foto dan cek apakah itu orang yang sama lewat cosine "
         "similarity di ruang PCA."),
        (f3, "🗜️", "Kompresi Gambar (SVD)", "badge-pink",
         "Upload gambar apa saja dan lihat bagaimana SVD bisa mengompresnya "
         "dengan berbagai tingkat kualitas."),
    ]
    for col, icon, title, badge_cls, desc in features:
        with col:
            with st.container(border=True):
                st.markdown(
                    f'<span class="badge {badge_cls}">{icon} {title}</span>',
                    unsafe_allow_html=True,
                )
                st.write(desc)

    st.markdown("### Cara Kerja Singkat")
    with st.container(border=True):
        st.write(
            "Setiap foto wajah diubah jadi grayscale, disamakan pencahayaannya, "
            "diubah ukurannya jadi 100×100 piksel, lalu diproyeksikan ke ruang "
            "PCA hasil training. Kemiripan dua wajah diukur lewat cosine "
            "similarity antar vektor PCA-nya — semakin mendekati 1, semakin "
            "mirip kedua wajah tersebut."
        )


# =========================================================
# PAGE: EDA & VISUALISASI
# =========================================================
def render_eda():
    st.markdown(
        """
        <div class="hero">
            <h1>📊 EDA & Visualisasi</h1>
            <p>Memahami data wajah dan cara PCA "melihat" wajah manusia.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    if y_train is None or pca is None:
        st.warning("Data model tidak lengkap untuk menampilkan EDA.")
        return

    with st.container(border=True):
        st.subheader("👥 Distribusi Foto per Identitas")
        counts = pd.Series(y_train).value_counts().sort_values(ascending=False)
        st.bar_chart(counts)
        st.caption(
            f"Rata-rata {counts.mean():.1f} foto per orang dari {len(counts)} identitas."
        )

    col1, col2 = st.columns(2)
    with col1:
        with st.container(border=True):
            st.subheader("🧠 Mean Face")
            mean_face = pca.mean_.reshape(100, 100)
            fig, ax = plt.subplots(figsize=(3, 3))
            ax.imshow(mean_face, cmap="gray")
            ax.axis("off")
            st.pyplot(fig, use_container_width=True)
            st.caption("Wajah rata-rata dari seluruh data training.")

    with col2:
        with st.container(border=True):
            st.subheader("📈 Explained Variance")
            cumvar = np.cumsum(pca.explained_variance_ratio_) * 100
            fig, ax = plt.subplots(figsize=(4, 3))
            ax.plot(cumvar, color="#7c3aed", linewidth=2.5)
            ax.fill_between(range(len(cumvar)), cumvar, color="#a855f7", alpha=0.15)
            ax.axhline(95, color="#ec4899", linestyle="--", label="95%")
            ax.set_xlabel("Jumlah Komponen")
            ax.set_ylabel("Variance (%)")
            ax.legend()
            ax.grid(alpha=0.2)
            st.pyplot(fig, use_container_width=True)
            st.caption(
                f"Total variance dipertahankan: {cumvar[-1]:.1f}% dengan "
                f"{pca.n_components_} komponen."
            )

    with st.container(border=True):
        st.subheader("👻 Top Eigenfaces")
        n_show = min(10, pca.components_.shape[0])
        cols = st.columns(n_show)
        for i, col in enumerate(cols):
            with col:
                fig, ax = plt.subplots(figsize=(2, 2))
                ax.imshow(pca.components_[i].reshape(100, 100), cmap="gray")
                ax.axis("off")
                ax.set_title(f"#{i + 1}", fontsize=9)
                st.pyplot(fig)

    if X_test_pca is not None and y_test is not None and X_train_pca is not None:
        with st.container(border=True):
            st.subheader("🎯 Akurasi Model (Pengenalan Wajah)")
            sims_matrix = cosine_similarity(X_test_pca, X_train_pca)
            best_idx = np.argmax(sims_matrix, axis=1)
            preds = np.array(y_train)[best_idx]
            acc = float(np.mean(preds == np.array(y_test)))
            st.metric("Akurasi pada data test", f"{acc * 100:.1f}%")
            st.caption(f"Diuji pada {len(y_test)} foto data test.")


# =========================================================
# PAGE: BANDINGKAN DUA WAJAH
# =========================================================
def render_compare():
    st.markdown(
        """
        <div class="hero">
            <h1>🔍 Bandingkan Dua Wajah</h1>
            <p>Upload dua foto, kita ukur seberapa "mirip" lewat cosine similarity
            di ruang PCA.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2 = st.columns(2)
    with col1:
        with st.container(border=True):
            foto_pertama = st.file_uploader(
                "📸 Foto Pertama", type=["jpg", "jpeg", "png"], key="foto1"
            )
            if foto_pertama:
                st.image(foto_pertama, use_container_width=True)
    with col2:
        with st.container(border=True):
            foto_kedua = st.file_uploader(
                "📸 Foto Kedua", type=["jpg", "jpeg", "png"], key="foto2"
            )
            if foto_kedua:
                st.image(foto_kedua, use_container_width=True)

    threshold = st.slider("Ambang batas kemiripan (threshold)", 0.0, 1.0, 0.50, 0.01)

    if foto_pertama and foto_kedua:
        if st.button("🔍 Bandingkan Sekarang"):
            face1 = preprocess(foto_pertama.getvalue())
            face2 = preprocess(foto_kedua.getvalue())

            z1 = pca.transform(face1.reshape(1, -1))
            z2 = pca.transform(face2.reshape(1, -1))
            sim = float(cosine_similarity(z1, z2)[0][0])

            with st.container(border=True):
                st.subheader("Hasil")
                st.progress(min(max(sim, 0.0), 1.0))
                st.metric("Cosine Similarity", f"{sim:.4f}")
                if sim >= threshold:
                    st.success("✅ SAMA ORANG")
                else:
                    st.error("❌ BEDA ORANG")


# =========================================================
# PAGE: KOMPRESI GAMBAR (SVD)
# =========================================================
def render_svd():
    st.markdown(
        """
        <div class="hero">
            <h1>🗜️ Kompresi Gambar dengan SVD</h1>
            <p>Singular Value Decomposition memecah gambar jadi komponen-komponen
            penting — makin sedikit komponen, makin kecil ukurannya (tapi makin
            blur).</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    uploaded = st.file_uploader(
        "Upload gambar (bebas, tidak harus wajah)",
        type=["jpg", "jpeg", "png"],
        key="svd_img",
    )

    if not uploaded:
        st.info("⬆️ Upload gambar untuk mulai bereksperimen dengan kompresi SVD.")
        return

    img = Image.open(uploaded)
    mode = st.radio("Mode warna", ["Grayscale", "Warna (RGB)"], horizontal=True)
    img_arr = (
        np.array(img.convert("L"))
        if mode == "Grayscale"
        else np.array(img.convert("RGB"))
    )

    h, w = img_arr.shape[:2]
    max_k = min(h, w, 300)
    default_k = min(50, max_k)
    k = st.slider("Jumlah komponen (k)", 1, max_k, default_k)

    if mode == "Grayscale":
        reconstructed, singular_values = svd_compress_gray(img_arr.astype(float), k)
    else:
        reconstructed, singular_values = svd_compress_color(img_arr.astype(float), k)

    col1, col2 = st.columns(2)
    with col1:
        with st.container(border=True):
            st.subheader("Asli")
            st.image(img_arr, use_container_width=True, clamp=True)
    with col2:
        with st.container(border=True):
            st.subheader(f"Hasil Kompresi (k={k})")
            st.image(reconstructed, use_container_width=True, clamp=True)

    n_channels = 1 if mode == "Grayscale" else 3
    original_size = h * w * n_channels
    compressed_size = k * (h + w + 1) * n_channels
    ratio = original_size / compressed_size

    m1, m2, m3 = st.columns(3)
    m1.metric("Ukuran Asli (nilai)", f"{original_size:,}")
    m2.metric("Ukuran Terkompresi (nilai)", f"{compressed_size:,}")
    m3.metric("Rasio Kompresi", f"{ratio:.1f}x")

    with st.container(border=True):
        st.subheader("📉 Singular Value Decay")
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.plot(singular_values, color="#db2777", linewidth=2)
        ax.axvline(k, color="#6366f1", linestyle="--", label=f"k={k}")
        ax.set_yscale("log")
        ax.set_xlabel("Index")
        ax.set_ylabel("Nilai Singular (skala log)")
        ax.legend()
        ax.grid(alpha=0.2)
        st.pyplot(fig, use_container_width=True)
        st.caption(
            "Sebagian besar 'informasi' gambar terkonsentrasi di singular value "
            "pertama — itulah mengapa gambar masih cukup jelas walau k kecil."
        )


# =========================================================
# ROUTER
# =========================================================
if page == "🏠 Home":
    render_home()
elif page == "📊 EDA & Visualisasi":
    render_eda()
elif page == "🔍 Bandingkan Dua Wajah":
    render_compare()
elif page == "🗜️ Kompresi Gambar (SVD)":
    render_svd()